source 'https://supermarket.chef.io'

cookbook 'tubmanproject_base', path: 'chef-repo/wrapper_cookbooks/tubmanproject_base'  
cookbook 'tubmanproject_github', path: 'chef-repo/wrapper_cookbooks/tubmanproject_github'
cookbook 'tubmanproject_nginx', path: 'chef-repo/wrapper_cookbooks/tubmanproject_nginx'
cookbook 'tubmanproject_python', path: 'chef-repo/wrapper_cookbooks/tubmanproject_python'
cookbook 'tubmanproject_nodejs', path: 'chef-repo/wrapper_cookbooks/tubmanproject_nodejs'
cookbook 'tubmanproject_supervisor', path: 'chef-repo/wrapper_cookbooks/tubmanproject_supervisor' 
cookbook 'tubmanproject_hosts', path: 'chef-repo/wrapper_cookbooks/tubmanproject_hosts'  
cookbook 'tubmanproject_aws', path: 'chef-repo/wrapper_cookbooks/tubmanproject_aws'
cookbook 'tubmanproject_docker', path: 'chef-repo/wrapper_cookbooks/tubmanproject_docker'
cookbook 'tubmanproject_mongodb', path: 'chef-repo/wrapper_cookbooks/tubmanproject_mongodb'
cookbook 'tubmanproject_jupyterhub', path: 'chef-repo/wrapper_cookbooks/tubmanproject_jupyterhub'
cookbook 'tubmanproject_app', path: 'chef-repo/wrapper_cookbooks/tubmanproject_app'